. $(brew --prefix asdf)/libexec/asdf.sh
alias ws='code ~/Workspaces/AllProjects.code-workspace'
alias ls='eza --long --header --git --group-directories-first'
alias la='ls --all'
alias ld='ls --tree --level=2'
alias lda='ld --all'
alias grep='rg'
alias grepi='rg -i'
alias grepn='rg -n'
alias grepc='rg --context 2'

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias ~='cd ~'